### ISSUE TITLE
jQuery Learning Center - Interactive tutorials for learn and other sites

### ISSUE THREAD

**Issue by AchoArnold** [jquery/content#10]
Develop a framework for the development and presentation of interactive tutorials. The system should contain some teaching material followed by a list of tasks that should be completed by the student to test their knowledge on the material presented. The teaching material could consist of videos and/or pdf slides. Each task that should be completed by the student will have hints that the student can reveal if they get stuck. The system should detect when the student has completed the task successfully, and offer the possibility to view the correct solution.

**Comment by agcolom** [comment]
There is already an issue opened for this at https://github.com/jquery/learn.jquery.com/issues/641 
I am closing this one as it is a duplicate.

**Comment by AchoArnold** [comment]
Sorry I had no idea. the page had aready been created. 
@agcolom It will also be nice If you could add a link to that issue on the Ideas page [here](https://github.com/jquery/gsoc/wiki/GSoC-2015-Ideas-List)

**Comment by agcolom** [comment]
@najela yes, good point. I will add this now. I will also add the list to how to submit a proposal on the issue to make sure this information is easy to find.
