### ISSUE TITLE
Access to trello

### ISSUE THREAD

**Issue by kumarrishav** [jquery/content#9]
User Name : kumarrishav
email: rishav006@gmail.com

**Comment by jacquerie** [comment]
I'm also interested.

Username: jacquerie
Email: `jacopo.notarstefano@gmail.com`

**Comment by agcolom** [comment]
I'll check with the team today during our meeting, but I don't think this would be terribly useful. There is nothing in Trello that isn't already in GH. I just use it to keep track of all my tasks across all GH content-related repos as a duplicate.

**Comment by arthurvr** [comment]
In the meeting we decided that the Trello board does not add much value for contributors. Thanks for the interest, though! We removed it from the readme as well.
